// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJQvZonX9chvdhibIat4sVW1tFpThl_rk',
    appId: '1:876732764191:web:21d9514b3c44a00f5c052a',
    messagingSenderId: '876732764191',
    projectId: 'molaknotes',
    authDomain: 'molaknotes.firebaseapp.com',
    databaseURL: 'https://molaknotes-default-rtdb.firebaseio.com',
    storageBucket: 'molaknotes.appspot.com',
    measurementId: 'G-GLTH2ZF6XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAP2Z5Tx0Sk5tpJccMZ86CBGsOGWCvUaY',
    appId: '1:876732764191:android:6ba4813506c8bb165c052a',
    messagingSenderId: '876732764191',
    projectId: 'molaknotes',
    databaseURL: 'https://molaknotes-default-rtdb.firebaseio.com',
    storageBucket: 'molaknotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjSbn5qfsjDqUlcFFQSfUU2KZr1c8gets',
    appId: '1:876732764191:ios:a1320479c3a5cfb35c052a',
    messagingSenderId: '876732764191',
    projectId: 'molaknotes',
    databaseURL: 'https://molaknotes-default-rtdb.firebaseio.com',
    storageBucket: 'molaknotes.appspot.com',
    iosClientId: '876732764191-kfkt62tdja7mrn02r017o288kcbem84p.apps.googleusercontent.com',
    iosBundleId: 'com.molaktycoon.molaknotes',
  );
}
